### ISSUE TITLE
3.4jar only not have jar

### ISSUE THREAD

**Issue by keqingyyds** [YuukiPS/DockerGS#37]
https://nightly.link/YuukiPS/DockerGS/workflows/DockerGS_GC_Alpine_3.4/main/DockerGS-GC.zip
NOT HAVE JAR

**Comment by obronca** [comment]
even if it has jar, you can't use it on 3.4.0, it's for 3.3.54

**Comment by obronca** [comment]
![3 4 50](https://user-images.githubusercontent.com/70872536/215377512-43b8f9f3-b2a4-41d5-97f9-f130bf0cfecc.png)

using the 3.4 docker gs, you'll get this, 3.4 beta*

**Comment by akbaryahya** [comment]
you need official 3.4 without beta, because proto beta and official version are different. btw the skill can't be used (a bug because the proto problem is still missing/incorrect)

**Comment by obronca** [comment]
But on screenshot i used 3.4.0 😳🤨 umm

**Comment by akbaryahya** [comment]
try https://github.com/YuukiPS/DockerGS/actions/runs/4040300239
