### ISSUE TITLE
运行3.6版本的找不到resource

### ISSUE THREAD

**Issue by dfmjndm** [YuukiPS/DockerGS#43]
运行readme中的docker配置指令
23:50:30 <INFO:Utils> Place a copy of 'BinOutput' and 'ExcelBinOutput' in the resources folder.
照理来说resources不是自动下载的吗
我在/var/lib/docker/volumes/resources中放入了resources
![image](https://user-images.githubusercontent.com/57401901/231610813-961e3855-cbf3-4831-9e85-09b76940b4aa.png)
没有效果，还是这个报错

**Comment by akbaryahya** [comment]
it should work now in new version,
